general {
    layout = dwindle
    resize_on_border = false
    allow_tearing = false
}

master {
    new_status = master
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

device {
	name = logitech-usb-receiver
	accel_profile = flat
}

device {
	name = logitech-g502-x-plus
	accel_profile = flat
}

device {
	name = logitech-g502-x-plus-1
	accel_profile = flat
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

	#scroll_factor = 0.75
    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

cursor {
	no_warps=true
    enable_hyprcursor = true
}

decoration {
    blur {
        enabled = true
        new_optimizations = yes
        contrast = 1
        brightness = 1

        vibrancy = 0.1696
    }

    shadow {
      render_power = 2
    }
}


misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
	middle_click_paste = false
}
