###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod+Shift+Alt, Q, exec, hyprctl kill # Pick and kill a window

binde = $mainMod, Minus, layoutmsg, splitratio -0.1
binde = $mainMod, Equal, layoutmsg, splitratio +0.1
binde = $mainMod, Semicolon, layoutmsg, splitratio -0.1
binde = $mainMod, Apostrophe, layoutmsg, splitratio +0.1

bind = $mainMod, Space, togglefloating,
bind = $mainMod, F, fullscreen, 0

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
