config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: false
dotfiles:
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_ags:
    src: config/ags
    dst: ~/.config/ags
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_fastfetch:
    src: config/fastfetch/config.jsonc
    dst: ~/.config/fastfetch/config.jsonc
    chmod: "744"
  f_fastfetch_ssh:
    src: config/fastfetch/config-ssh.jsonc
    dst: ~/.config/fastfetch/config-ssh.jsonc
    chmod: "744"
  f_fastfetch_wsl:
    src: config/fastfetch/config-wsl.jsonc
    dst: ~/.config/fastfetch/config.jsonc
    chmod: "744"
  d_fish:
    src: config/fish
    dst: ~/.config/fish
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_kvantum:
    src: config/Kvantum
    dst: ~/.config/Kvantum
  d_qt5ct:
    src: config/qt5ct
    dst: ~/.config/qt5ct
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: "700"
  d_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
  d_spicetify:
    src: config/spicetify
    dst: ~/.config/spicetify
    chmod: "700"
  f_fuzzel-emoji:
    src: local/bin/fuzzel-emoji
    dst: ~/.local/bin/fuzzel-emoji
    chmod: "755"
  f_rubyshot:
    src: local/bin/rubyshot
    dst: ~/.local/bin/rubyshot
    chmod: "755"
  f_wallpaper.png:
    src: Pictures/wallpaper.png
    dst: ~/Pictures/wallpaper.png
  f_fetch_logo.png:
    src: Pictures/fetch_logo.png
    dst: ~/Pictures/fetch_logo.png
  d_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
  d_fusuma:
    src: config/fusuma
    dst: ~/.config/fusuma
  f_btop.conf:
    src: config/btop/btop.conf
    dst: ~/.config/btop/btop.conf
  f_ferdium_user.css:
    src: config/Ferdium/recipes/whatsapp/user.css
    dst: ~/.config/Ferdium/recipes/whatsapp/user.css
  f_ferdium_darkmode.css:
    src: config/Ferdium/recipes/whatsapp/darkmode.css
    dst: ~/.config/Ferdium/recipes/whatsapp/darkmode.css
  f_ferdium_user.js:
    src: config/Ferdium/recipes/whatsapp/user.js
    dst: ~/.config/Ferdium/recipes/whatsapp/user.js
  f_electron-flags.conf:
    src: config/electron-flags.conf
    dst: ~/.config/electron-flags.conf
  d_waynergy:
    src: config/waynergy
    dst: ~/.config/waynergy
  d_xkb:
    src: config/xkb
    dst: ~/.config/xkb
  d_oh_my_posh:
    src: config/oh-my-posh
    dst: ~/.config/oh-my-posh
  d_atac:
    src: config/atac
    dst: ~/.config/atac
  d_ff_chrome:
    src: mozilla/firefox/chrome
    dst: ~/.mozilla/firefox/chrome
  f_ff_user:
    src: mozilla/firefox/user.js
    dst: ~/.mozilla/firefox/user.js
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_zen_user:
    src: zen/user.js
    dst: ~/.zen/user.js
  d_commitlint:
    src: config/commitlint
    dst: ~/.config/commitlint
    chmod: "750"
profiles:
  yugen-work:
    dotfiles:
      - d_hypr
      - d_ags
      - d_nvim
      - f_fastfetch
      - f_fastfetch_ssh
      - d_fish
      - d_kitty
      - d_kvantum
      - d_qt5ct
      - d_gtk-3.0
      - d_gtk-4.0
      - d_spicetify
      - f_fuzzel-emoji
      - f_rubyshot
      - f_wallpaper.png
      - f_fetch_logo.png
      - d_fuzzel
      - d_fusuma
      - f_btop.conf
      - f_ferdium_user.css
      - f_ferdium_darkmode.css
      - f_ferdium_user.js
      - f_electron-flags.conf
      - d_waynergy
      - d_xkb
      - d_oh_my_posh
      - d_atac
        # - d_ff_chrome
        # - f_ff_user
      - d_lazygit
      - f_gitignore
      - f_gitconfig
      - f_zen_user
      - d_commitlint
  jurien-wsl:
    dotfiles:
      - d_nvim
      - f_fastfetch_wsl
      - d_fish
      - d_oh_my_posh
      - d_atac
      - d_lazygit
      - f_gitignore
      - f_gitconfig
