# https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

swipe:
  3:
    left:
      command: "ydotool key 1:1 1:0 && ydotool key 29:1 125:1 38:1 38:0 125:0 29:0"
    right:
      command: "ydotool key 1:1 1:0 && ydotool key 29:1 125:1 35:1 35:0 125:0 29:0"
    up:
      command: "ydotool key 1:1 1:0 && ydotool key 125:1 32:1 32:0 125:0"
    down:
      command: "ydotool key 1:1 1:0 && ydotool key 125:1 49:1 49:0 125:0"

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
