source = ~/dots/dotfiles/config/hypr/shared/index.conf


source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/execs.conf
source = ~/.config/hypr/config/macropad-keybinds.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/rules.conf
#source = ~/.config/hypr/config/scrolling.conf
source = ~/.config/hypr/config/hy3.conf
