enabled: true
use-emoji: true

rules:
  header-trim: [2]
  type-case: [2, "always", "lowercase"]
  type-empty: [2, "never"]
  type-enum:
    [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ]
  subject-case: [2, "never", ["pascal-case", "upper-case"]]
  subject-empty: [2, "never"]
  subject-full-stop: [2, "never", "."]
  body-leading-blank: [1, "always"]
  body-max-line-length: [2, "always", 100]
  footer-leading-blank: [1, "always"]
  footer-max-line-length: [2, "always", 144]
